# Keep it boring. Needed later for NVIDIA tearing; optional in the VM.
backend = "xrender";
vsync = true;
shadow = false;
fading = false;
inactive-opacity = 1.0;
frame-opacity = 1.0;
corner-radius = 0;
wintypes: {
  tooltip = { fade = false; shadow = false; }
}
